MAX_ASSISTANT_MESSAGE_CHARS = 8000
MAX_ASSISTANT_HISTORY_MESSAGES = 12
MAX_ASSISTANT_HISTORY_TOTAL_CHARS = 24000
MAX_ASSISTANT_HISTORY_MESSAGE_CHARS = 8000
MAX_UI_CONTEXT_CHARS = 2000
MAX_ASSISTANT_ROUNDS = 6
