MAX_JOB_ATTEMPTS = 3
STALE_LOCK_MINUTES = 15
MAX_LAST_ERROR_LENGTH = 1000
WORKER_IDLE_SLEEP_SECONDS = 2
SCHEDULER_MAINTENANCE_INTERVAL_SECONDS = 60

JOB_STATUS_PENDING = "pending"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_DONE = "done"
JOB_STATUS_FAILED = "failed"

JOB_TYPE_EMBED_OBJECT = "embed_object"
JOB_TYPE_INGEST_LOCAL_FILE = "ingest_local_file"
JOB_TYPE_SUMMARIZE_RESOURCE = "summarize_resource"
JOB_TYPE_CORRELATE_OBJECT = "correlate_object"

JOB_TYPE_SYNC_GOOGLE_GMAIL = "sync_google_gmail"
JOB_TYPE_SYNC_GOOGLE_CALENDAR = "sync_google_calendar"
JOB_TYPE_SYNC_YANDEX_MAIL = "sync_yandex_mail"
JOB_TYPE_SYNC_YANDEX_CALENDAR = "sync_yandex_calendar"

RECURRING_SOURCE_JOB_TYPES = frozenset(
    {
        JOB_TYPE_SYNC_GOOGLE_GMAIL,
        JOB_TYPE_SYNC_GOOGLE_CALENDAR,
        JOB_TYPE_SYNC_YANDEX_MAIL,
        JOB_TYPE_SYNC_YANDEX_CALENDAR,
    }
)

SOURCE_SYNC_INTERVAL_SECONDS = {
    JOB_TYPE_SYNC_GOOGLE_GMAIL: 120,
    JOB_TYPE_SYNC_YANDEX_MAIL: 120,
    JOB_TYPE_SYNC_GOOGLE_CALENDAR: 300,
    JOB_TYPE_SYNC_YANDEX_CALENDAR: 300,
}

RECURRING_FAILED_REARM_SECONDS = 3600

RETRY_BACKOFF_SECONDS = {
    1: 10,
    2: 60,
}
