MAX_JOB_ATTEMPTS = 3
STALE_LOCK_MINUTES = 15
MAX_LAST_ERROR_LENGTH = 1000
WORKER_IDLE_SLEEP_SECONDS = 2

JOB_STATUS_PENDING = "pending"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_DONE = "done"
JOB_STATUS_FAILED = "failed"

JOB_TYPE_EMBED_OBJECT = "embed_object"
JOB_TYPE_INGEST_LOCAL_FILE = "ingest_local_file"
JOB_TYPE_SUMMARIZE_RESOURCE = "summarize_resource"
JOB_TYPE_CORRELATE_OBJECT = "correlate_object"

RETRY_BACKOFF_SECONDS = {
    1: 10,
    2: 60,
}
