"""PHASE 26B client-assisted intake bounds."""

CLIENT_REPRESENTATION_KINDS = frozenset(
    {"full", "chunk", "schema", "sample", "statistics"}
)

MAX_CLIENT_REPRESENTATION_PARTS = 64
MAX_CLIENT_REPRESENTATION_PART_CHARS = 16 * 1024
MAX_CLIENT_REPRESENTATION_TOTAL_CHARS = 256 * 1024

MAX_EMAIL_ATTACHMENTS_PER_MESSAGE = 20
MAX_EMAIL_ATTACHMENT_BYTES = 10 * 1024 * 1024
MAX_EMAIL_ATTACHMENT_BYTES_PER_MESSAGE = 20 * 1024 * 1024

ATTACHMENT_TEXT_SUFFIXES = frozenset({".txt", ".md", ".csv"})
