KIND_LABEL = "label"
EDGE_TYPE_LABELED_WITH = "labeled_with"
LABEL_SCHEMA_VERSION = 1
LABEL_NAME_MAX_CHARS = 80
LIST_LABELS_MAX = 200
QUERY_LABEL_IDS_MAX = 8
LABEL_MATCH_ALL = "all"
LABEL_MATCH_ANY = "any"
