KIND_SCHEDULED_ACTIVITY = "scheduled_activity"

SCHEDULE_KIND_ONCE = "once"

SCHEDULED_ACTIVITY_STATUS_SCHEDULED = "scheduled"
SCHEDULED_ACTIVITY_STATUS_COMPLETED = "completed"
SCHEDULED_ACTIVITY_STATUS_CANCELLED = "cancelled"

SCHEDULED_ACTIVITY_STATUSES = frozenset(
    {
        SCHEDULED_ACTIVITY_STATUS_SCHEDULED,
        SCHEDULED_ACTIVITY_STATUS_COMPLETED,
        SCHEDULED_ACTIVITY_STATUS_CANCELLED,
    }
)

METADATA_SCHEDULE_KIND = "schedule_kind"
METADATA_PRIORITY = "priority"

NOTIFICATION_PROPOSAL_TYPE = "scheduled_activity"
