DEFAULT_IMAP_HOST = "imap.yandex.ru"
DEFAULT_IMAP_PORT = 993
DEFAULT_MAIL_FOLDER = "INBOX"
DEFAULT_CALDAV_HOST = "caldav.yandex.ru"
DEFAULT_CALDAV_BASE_URL = "https://caldav.yandex.ru"

DEFAULT_SYNC_DAYS = 30
MAX_SYNC_DAYS = 90
DEFAULT_SYNC_LIMIT = 50
MAX_SYNC_LIMIT = 100

DEFAULT_CALENDAR_SYNC_DAYS_BACK = 60
MAX_CALENDAR_SYNC_DAYS_BACK = 90
DEFAULT_CALENDAR_SYNC_DAYS_FORWARD = 90
MAX_CALENDAR_SYNC_DAYS_FORWARD = 90
DEFAULT_CALENDAR_SYNC_LIMIT = 100
MAX_CALENDAR_SYNC_LIMIT = 100
MAX_CALENDAR_SYNC_CALENDARS = 10

MAX_EMAIL_BODY_CHARS = 8000
MAX_EVENT_BODY_CHARS = 8000
