DEFAULT_IMAP_HOST = "imap.yandex.ru"
DEFAULT_IMAP_PORT = 993
DEFAULT_MAIL_FOLDER = "INBOX"

DEFAULT_SYNC_DAYS = 30
MAX_SYNC_DAYS = 90
DEFAULT_SYNC_LIMIT = 50
MAX_SYNC_LIMIT = 100

MAX_EMAIL_BODY_CHARS = 8000
